/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author patob
 */
public class ventanaMirasol extends javax.swing.JFrame {
    public controladorAgencia cag = new controladorAgencia();
    String valores[][]=new String[15][5];
    /**
     * Creates new form ventanaMirasol
     */
    public ventanaMirasol() {
        initComponents();
        cargarDatos(nAgencia());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combo_agencia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        spinner_mes = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        textF_ventas = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_agencia = new javax.swing.JTable();
        botonExportar = new javax.swing.JButton();
        labelHistorial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Mirasol");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 80, 26);

        jLabel2.setText("Agencia :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 50, 16);

        combo_agencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agencia 1", "Agencia 2", "Agencia 3", "Agencia 4", "Agencia 5" }));
        combo_agencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_agenciaActionPerformed(evt);
            }
        });
        getContentPane().add(combo_agencia);
        combo_agencia.setBounds(100, 50, 90, 30);

        jLabel3.setText("Mes :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 60, 41, 16);

        spinner_mes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spinner_mes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner_mesStateChanged(evt);
            }
        });
        spinner_mes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spinner_mesMouseClicked(evt);
            }
        });
        getContentPane().add(spinner_mes);
        spinner_mes.setBounds(320, 50, 90, 30);

        jLabel4.setText("Ventas :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 110, 50, 16);
        getContentPane().add(textF_ventas);
        textF_ventas.setBounds(100, 100, 90, 30);

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar);
        botonGuardar.setBounds(270, 100, 140, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 150, 440, 10);

        tabla_agencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Agencia 1", "Agencia 2", "Agencia 3", "Agencia 4", "Agencia 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_agencia);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 420, 270);

        botonExportar.setText("Exportar");
        botonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExportarActionPerformed(evt);
            }
        });
        getContentPane().add(botonExportar);
        botonExportar.setBounds(300, 490, 120, 40);

        labelHistorial.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        getContentPane().add(labelHistorial);
        labelHistorial.setBounds(10, 430, 410, 40);

        setBounds(0, 0, 451, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_agenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_agenciaActionPerformed
        cargarDatos(nAgencia());
    }//GEN-LAST:event_combo_agenciaActionPerformed

    private void spinner_mesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinner_mesMouseClicked
        cargarDatos(nAgencia());
    }//GEN-LAST:event_spinner_mesMouseClicked

    private void spinner_mesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner_mesStateChanged
        cargarDatos(nAgencia());
    }//GEN-LAST:event_spinner_mesStateChanged

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if(textF_ventas.getText().length()!=0){
           cag.getAg()[nAgencia()].getM()[(int)spinner_mes.getValue()-1].setVentas(Double.parseDouble(textF_ventas.getText())); 
            cargarTabla();
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        }
        cargarDatos(nAgencia());
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExportarActionPerformed
        crearJson crj = new crearJson();
        try {
            crj.generarArchivo(cag);
        } catch (IOException ex) {
            Logger.getLogger(ventanaMirasol.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonExportarActionPerformed
    
    private int nAgencia(){
        int val=-1;
        switch (combo_agencia.getSelectedItem().toString()) {
            case "Agencia 1":
                val=0;
                break;
            case "Agencia 2":
                val=1;
                break;
            case "Agencia 3":
                val=2;
                break;
            case "Agencia 4":
                val=3;
                break;
            case "Agencia 5":
                val=4;
                break;
            default:
                throw new AssertionError();
        }
        return val;
    }
    
    private void cargarDatos(int val){
        textF_ventas.setText(cag.getAg()[val].getM()[(int)spinner_mes.getValue()-1].getVentas()+"");
    }
    private void cargarTabla (){
        String columnasNombre []={"Agencia 1","Agencia 2","Agencia 3","Agencia 4","Agencia 5"};
        
        for (int i = 0; i < valores.length; i++) {
            for (int j = 0; j < valores[0].length; j++) {
                if(i<12){
                   valores[i][j]=cag.getAg()[j].getM()[i].getVentas()+""; 
                }else if(i==12){
                        valores[i][j]=" ";
                    }else if(i==13){
                            valores[i][j]=cag.calcularPromedio(j)+"";
                        }else{
                            valores[i][j]=cag.calcularValor(j)+"";
                }
            }
        }
        tabla_agencia.setModel(new DefaultTableModel(valores, columnasNombre));
        labelHistorial.setText(cag.mostrarHistorial());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaMirasol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaMirasol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaMirasol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaMirasol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaMirasol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonExportar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JComboBox<String> combo_agencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelHistorial;
    private javax.swing.JSpinner spinner_mes;
    private javax.swing.JTable tabla_agencia;
    private javax.swing.JTextField textF_ventas;
    // End of variables declaration//GEN-END:variables
}
